export const CARDS = {
  clb_1: { id: 'clb_1', name: 'Ace of Clubs' },
  clb_2: { id: 'clb_2', name: 'Two of Clubs' },
  clb_3: { id: 'clb_3', name: 'Three of Clubs' },
  clb_4: { id: 'clb_4', name: 'Four of Clubs' },
  clb_5: { id: 'clb_5', name: 'Five of Clubs' },
  clb_6: { id: 'clb_6', name: 'Six of Clubs' },
  clb_7: { id: 'clb_7', name: 'Seven of Clubs' },
  clb_8: { id: 'clb_8', name: 'Eight of Clubs' },
  clb_9: { id: 'clb_9', name: 'Nine of Clubs' },
  clb_10: { id: 'clb_10', name: 'Ten of Clubs' },
  clb_jack: { id: 'clb_jack', name: 'Jack of Clubs' },
  clb_queen: { id: 'clb_queen', name: 'Queen of Clubs' },
  clb_king: { id: 'clb_king', name: 'King of Clubs' },
  dmd_1: { id: 'dmd_1', name: 'Ace of Diamonds' },
  dmd_2: { id: 'dmd_2', name: 'Two of Diamonds' },
  dmd_3: { id: 'dmd_3', name: 'Three of Diamonds' },
  dmd_4: { id: 'dmd_4', name: 'Four of Diamonds' },
  dmd_5: { id: 'dmd_5', name: 'Five of Diamonds' },
  dmd_6: { id: 'dmd_6', name: 'Six of Diamonds' },
  dmd_7: { id: 'dmd_7', name: 'Seven of Diamonds' },
  dmd_8: { id: 'dmd_8', name: 'Eight of Diamonds' },
  dmd_9: { id: 'dmd_9', name: 'Nine of Diamonds' },
  dmd_10: { id: 'dmd_10', name: 'Ten of Diamonds' },
  dmd_jack: { id: 'dmd_jack', name: 'Jack of Diamonds' },
  dmd_queen: { id: 'dmd_queen', name: 'Queen of Diamonds' },
  dmd_king: { id: 'dmd_king', name: 'King of Diamonds' },
  hrt_1: { id: 'hrt_1', name: 'Ace of Hearts' },
  hrt_2: { id: 'hrt_2', name: 'Two of Hearts' },
  hrt_3: { id: 'hrt_3', name: 'Three of Hearts' },
  hrt_4: { id: 'hrt_4', name: 'Four of Hearts' },
  hrt_5: { id: 'hrt_5', name: 'Five of Hearts' },
  hrt_6: { id: 'hrt_6', name: 'Six of Hearts' },
  hrt_7: { id: 'hrt_7', name: 'Seven of Hearts' },
  hrt_8: { id: 'hrt_8', name: 'Eight of Hearts' },
  hrt_9: { id: 'hrt_9', name: 'Nine of Hearts' },
  hrt_10: { id: 'hrt_10', name: 'Ten of Hearts' },
  hrt_jack: { id: 'hrt_jack', name: 'Jack of Hearts' },
  hrt_queen: { id: 'hrt_queen', name: 'Queen of Hearts' },
  hrt_king: { id: 'hrt_king', name: 'King of Hearts' },
  spd_1: { id: 'spd_1', name: 'Ace of Spades' },
  spd_2: { id: 'spd_2', name: 'Two of Spades' },
  spd_3: { id: 'spd_3', name: 'Three of Spades' },
  spd_4: { id: 'spd_4', name: 'Four of Spades' },
  spd_5: { id: 'spd_5', name: 'Five of Spades' },
  spd_6: { id: 'spd_6', name: 'Six of Spades' },
  spd_7: { id: 'spd_7', name: 'Seven of Spades' },
  spd_8: { id: 'spd_8', name: 'Eight of Spades' },
  spd_9: { id: 'spd_9', name: 'Nine of Spades' },
  spd_10: { id: 'spd_10', name: 'Ten of Spades' },
  spd_jack: { id: 'spd_jack', name: 'Jack of Spades' },
  spd_queen: { id: 'spd_queen', name: 'Queen of Spades' },
  spd_king: { id: 'spd_king', name: 'King of Spades' },
};

export const STACKS = {
  stk_1: { id: 'stk_1', cards: [] },
  stk_2: { id: 'stk_2', cards: [] },
  stk_3: { id: 'stk_3', cards: [] },
  stk_4: { id: 'stk_4', cards: [] },
  stk_5: { id: 'stk_5', cards: [] },
  stk_6: { id: 'stk_6', cards: [] },
  stk_7: { id: 'stk_7', cards: [] },
};
