import { Card, Stack } from '@/types';

export const CARDS = {
  clb_1: {
    id: 'clb_1',
    name: 'Ace of Clubs',
    spriteCoords: { row: 2, col: 0 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_2: {
    id: 'clb_2',
    name: 'Two of Clubs',
    spriteCoords: { row: 2, col: 1 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_3: {
    id: 'clb_3',
    name: 'Three of Clubs',
    spriteCoords: { row: 2, col: 2 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_4: {
    id: 'clb_4',
    name: 'Four of Clubs',
    spriteCoords: { row: 2, col: 3 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_5: {
    id: 'clb_5',
    name: 'Five of Clubs',
    spriteCoords: { row: 2, col: 4 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_6: {
    id: 'clb_6',
    name: 'Six of Clubs',
    spriteCoords: { row: 2, col: 5 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_7: {
    id: 'clb_7',
    name: 'Seven of Clubs',
    spriteCoords: { row: 2, col: 6 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_8: {
    id: 'clb_8',
    name: 'Eight of Clubs',
    spriteCoords: { row: 2, col: 7 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_9: {
    id: 'clb_9',
    name: 'Nine of Clubs',
    spriteCoords: { row: 2, col: 8 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_10: {
    id: 'clb_10',
    name: 'Ten of Clubs',
    spriteCoords: { row: 2, col: 9 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_jack: {
    id: 'clb_jack',
    name: 'Jack of Clubs',
    spriteCoords: { row: 2, col: 10 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_queen: {
    id: 'clb_queen',
    name: 'Queen of Clubs',
    spriteCoords: { row: 2, col: 11 },
    child: null,
    parent: null,
    hidden: false,
  },
  clb_king: {
    id: 'clb_king',
    name: 'King of Clubs',
    spriteCoords: { row: 2, col: 12 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_1: {
    id: 'dmd_1',
    name: 'Ace of Diamonds',
    spriteCoords: { row: 1, col: 0 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_2: {
    id: 'dmd_2',
    name: 'Two of Diamonds',
    spriteCoords: { row: 1, col: 1 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_3: {
    id: 'dmd_3',
    name: 'Three of Diamonds',
    spriteCoords: { row: 1, col: 2 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_4: {
    id: 'dmd_4',
    name: 'Four of Diamonds',
    spriteCoords: { row: 1, col: 3 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_5: {
    id: 'dmd_5',
    name: 'Five of Diamonds',
    spriteCoords: { row: 1, col: 4 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_6: {
    id: 'dmd_6',
    name: 'Six of Diamonds',
    spriteCoords: { row: 1, col: 5 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_7: {
    id: 'dmd_7',
    name: 'Seven of Diamonds',
    spriteCoords: { row: 1, col: 6 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_8: {
    id: 'dmd_8',
    name: 'Eight of Diamonds',
    spriteCoords: { row: 1, col: 7 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_9: {
    id: 'dmd_9',
    name: 'Nine of Diamonds',
    spriteCoords: { row: 1, col: 8 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_10: {
    id: 'dmd_10',
    name: 'Ten of Diamonds',
    spriteCoords: { row: 1, col: 9 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_jack: {
    id: 'dmd_jack',
    name: 'Jack of Diamonds',
    spriteCoords: { row: 1, col: 10 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_queen: {
    id: 'dmd_queen',
    name: 'Queen of Diamonds',
    spriteCoords: { row: 1, col: 11 },
    child: null,
    parent: null,
    hidden: false,
  },
  dmd_king: {
    id: 'dmd_king',
    name: 'King of Diamonds',
    spriteCoords: { row: 1, col: 12 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_1: {
    id: 'hrt_1',
    name: 'Ace of Hearts',
    spriteCoords: { row: 0, col: 0 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_2: {
    id: 'hrt_2',
    name: 'Two of Hearts',
    spriteCoords: { row: 0, col: 1 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_3: {
    id: 'hrt_3',
    name: 'Three of Hearts',
    spriteCoords: { row: 0, col: 2 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_4: {
    id: 'hrt_4',
    name: 'Four of Hearts',
    spriteCoords: { row: 0, col: 3 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_5: {
    id: 'hrt_5',
    name: 'Five of Hearts',
    spriteCoords: { row: 0, col: 4 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_6: {
    id: 'hrt_6',
    name: 'Six of Hearts',
    spriteCoords: { row: 0, col: 5 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_7: {
    id: 'hrt_7',
    name: 'Seven of Hearts',
    spriteCoords: { row: 0, col: 6 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_8: {
    id: 'hrt_8',
    name: 'Eight of Hearts',
    spriteCoords: { row: 0, col: 7 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_9: {
    id: 'hrt_9',
    name: 'Nine of Hearts',
    spriteCoords: { row: 0, col: 8 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_10: {
    id: 'hrt_10',
    name: 'Ten of Hearts',
    spriteCoords: { row: 0, col: 9 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_jack: {
    id: 'hrt_jack',
    name: 'Jack of Hearts',
    spriteCoords: { row: 0, col: 10 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_queen: {
    id: 'hrt_queen',
    name: 'Queen of Hearts',
    spriteCoords: { row: 0, col: 11 },
    child: null,
    parent: null,
    hidden: false,
  },
  hrt_king: {
    id: 'hrt_king',
    name: 'King of Hearts',
    spriteCoords: { row: 0, col: 12 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_1: {
    id: 'spd_1',
    name: 'Ace of Spades',
    spriteCoords: { row: 3, col: 0 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_2: {
    id: 'spd_2',
    name: 'Two of Spades',
    spriteCoords: { row: 3, col: 1 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_3: {
    id: 'spd_3',
    name: 'Three of Spades',
    spriteCoords: { row: 3, col: 2 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_4: {
    id: 'spd_4',
    name: 'Four of Spades',
    spriteCoords: { row: 3, col: 3 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_5: {
    id: 'spd_5',
    name: 'Five of Spades',
    spriteCoords: { row: 3, col: 4 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_6: {
    id: 'spd_6',
    name: 'Six of Spades',
    spriteCoords: { row: 3, col: 5 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_7: {
    id: 'spd_7',
    name: 'Seven of Spades',
    spriteCoords: { row: 3, col: 6 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_8: {
    id: 'spd_8',
    name: 'Eight of Spades',
    spriteCoords: { row: 3, col: 7 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_9: {
    id: 'spd_9',
    name: 'Nine of Spades',
    spriteCoords: { row: 3, col: 8 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_10: {
    id: 'spd_10',
    name: 'Ten of Spades',
    spriteCoords: { row: 3, col: 9 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_jack: {
    id: 'spd_jack',
    name: 'Jack of Spades',
    spriteCoords: { row: 3, col: 10 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_queen: {
    id: 'spd_queen',
    name: 'Queen of Spades',
    spriteCoords: { row: 3, col: 11 },
    child: null,
    parent: null,
    hidden: false,
  },
  spd_king: {
    id: 'spd_king',
    name: 'King of Spades',
    spriteCoords: { row: 3, col: 12 },
    child: null,
    parent: null,
    hidden: false,
  },
} as Record<string, Card>;

export const STACKS = {
  stk_1: { id: 'stk_1', child: null },
  stk_2: { id: 'stk_2', child: null },
  stk_3: { id: 'stk_3', child: null },
  stk_4: { id: 'stk_4', child: null },
  stk_5: { id: 'stk_5', child: null },
  stk_6: { id: 'stk_6', child: null },
  stk_7: { id: 'stk_7', child: null },
} as Record<string, Stack>;

// default set
export const TILE_SCALE = 1.8;
export const CARD_PADDING = 15 * TILE_SCALE;
export const CARD_BACK_COORDS = { row: 1, col: 13 } as const;
export const TILEMAP_VALUES = {
  frontUrl: '/cards_tilemap.png',
  backUrl: '/cards_tilemap.png',
  totalWidth: 909 * TILE_SCALE,
  totalHeight: 259 * TILE_SCALE,
  totalWidthBack: 909 * TILE_SCALE,
  totalHeightBack: 259 * TILE_SCALE,
  marginHorizontal: 11,
  marginVertical: 2,
  stepHorizontal: 65,
  stepVertical: 65,
  tileWidth: 42 * TILE_SCALE,
  tileHeight: 60 * TILE_SCALE,
  backTileCoords: { row: 1, col: 13 },
  backgroundTileCoords: null,
} as const;

// balatro set
// export const TILE_SCALE = 1.2;
// export const CARD_PADDING = 21 * TILE_SCALE;
// export const TILEMAP_VALUES = {
//   frontUrl: '/cards_tilemap_b_front.png',
//   backUrl: '/cards_tilemap_b_back.png',
//   totalWidth: 923 * TILE_SCALE,
//   totalHeight: 380 * TILE_SCALE,
//   totalWidthBack: 497 * TILE_SCALE,
//   totalHeightBack: 475 * TILE_SCALE,
//   marginHorizontal: 0,
//   marginVertical: 0,
//   stepHorizontal: 71,
//   stepVertical: 95,
//   tileWidth: 71 * TILE_SCALE,
//   tileHeight: 95 * TILE_SCALE,
//   backTileCoords: { row: 2, col: 4 },
//   backgroundTileCoords: { row: 0, col: 1 },
// } as const;

export const FOUNDATION_DROPPABLE_ID = 'foundation';

export const SUITS = ['clb', 'dmd', 'hrt', 'spd'] as const;
